### ISSUE TITLE
No instructions for daughter board headers

### ISSUE THREAD

**Issue by MarshM4ll0w** [BadgePiratesLLC/DefCon_SecKC_26#9]
I contacted the badge pirates twitter account looking for instructions on how to solder on the headers to both the daughter board and the main board.  It looks fairly self explanatory, but that's how I always mess things up.  They told me to search for the tutorial on github, but it doesn't exist.  Am I missing something?  Thanks, in advance, for your time.

**Comment by flightgod** [comment]
Sorry for the confusion, you can solder the headers on either the front or back of badge. If you do the back I would recommend replacing the batteries with a lipo, it will fit better (there on instructions). If you are wanting to use the board as a development platform them solder on the front, and put on a lipo (highly recommended).
